<?php
// $Id$
/**
 * @file
 * Lets users to manipulate with images group (slider)
 * 
 * Only authenticated users can add images to to slider
 * and slider will slide them.
 */


/*
 * Display help and module information
 * @param path which path of the site we're diplaying help
 * @param arg array that holds the current path as would we be returned from arg() function
 * @return help text for the path
 */
function slider_help($path, $arg) {
    $output = '';
    switch ($output){
        case 'admin/modules#description':
            $output = '<p>'. t('Slider for images.') .'</p>';
            break;
        case 'admin/help#slider':
            $output = t('<p>The administrator can add images to Slider, as a content.
                Slider can slide them, and the user can rearange the position of images.</p>');
            break;
    }
    
    return $output;
} // end slider_help

/**
 * Implementation of hook_block()
 */
function slider_block($op = 'list', $delta = 0) {
    // Add js and css
    drupal_add_js(drupal_get_path('module', 'slider') . '/js/slider.js');
    drupal_add_css(drupal_get_path('module', 'slider') . '/css/slider.css');
    
    if ($op == 'list') {
        // Get the list of nodeblock nodes from database.
        $result = db_query("SELECT nid FROM {node} WHERE type='sliderimages'");
        $blocks = array();
        while ($row = db_fetch_object($result)) {
            $node = node_load($row->nid);
            $blocks[$row->nid]['info'] = check_plain($node->title);
        }
        return $blocks;
    } elseif ($op == 'view') {
        // Don't show on own node page
        if (arg(0) == 'node' && arg(1) == $delta) {
            return;
        }
        // Load the node if it's published.
        if ($node = node_load(array('nid' => $delta, 'status' => 1))) {
            // Don't show nodes in other languages than current. Integration with i18n node languages.
            //maybe later: global $language;
            //if (empty($node->language) || $node->language == $language->language) {
                return array(
                    'subject' => '',
                    'content' => sliderimages_block_content($node),
                );
            //}
        }
    }
 }

 /**
  * Implementation of block content function
  * @param type $node
  * @return type
  */
function sliderimages_block_content($node) {
    $node->build_mode = NODEASBLOCK_BUILD_TEASER;
    $node = node_build_content($node, TRUE, FALSE);
    $node->body = drupal_render($node->content);
    
    return theme('sliderimages', $node);
}

/**
 * Implementation of hook_theme()
 * 
 * @param type $existing
 * @param type $type
 * @param type $theme
 * @param type $path
 */
function slider_theme($existing, $type, $theme, $path) {
    return array(
        'sliderimages' => array(
            'template' => 'templates/node-sliderimages',
            'arguments' => array(
                'node' => NULL
            )
    ));
}