<?php
// $Id$ faqpanels.module,v 1.0 2011/02/07 11:20:07 chriscalip Exp $

/**
 * Implementation of hook_ctools_plugin_directory() to let the system know
 * where our task and task_handler plugins are.
 */
function faqpanels_ctools_plugin_directory($owner, $plugin_type) {
  $allowed_owners = array('ctools', 'page_manager');
  if (!in_array($owner, $allowed_owners)) {
    return;
  }
  $allowed_plugin_types = array('content_types', 'tasks');
  if (!in_array($plugin_type, $allowed_plugin_types)) {
    return;
  }  
  return "plugins/$plugin_type";
}